version: "3"


services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=devpass
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "gunicorn djangoProject.wsgi -b 0.0.0.0:8000 --reload & celery -A djangoProject worker --loglevel=debug"
    volumes:
      - ./:/usr/src/app
      - /static:/static
    depends_on:
      - postgresdb
    ports:
    - "8000:8000"
    restart:
      "always"

  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - postgresdb

  # celery:
  #   build: ./
  #   command: celery -A djangoProject worker -l INFO
  #   volumes:
  #     - ./:/usr/src/app
  #   depends_on:
  #     # - redis
  #     # - postgresdb
  #     - web
  #     - redis

  # celery-beat:
  #   build: .
  #   command: celery -A djangoProject beat -l info
  #   depends_on:
  #     - redis
  #     - postgresdb
  #     - web



  # nginx:
  #   build:
  #     context: ./docker/nginx
  #     dockerfile: Dockerfile
  #   # depends_on:
  #   #   - web
  #   #   - postgresdb
  #   ports:
  #   - "80:80"
  #   volumes:
  #   - ./static/:/static
